FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04

# Avoid interactive apt prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install basic tools
RUN sudo apt-get update && sudo apt-get install -y \
    flex 